name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Starting CI

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: 6.0.x
          include-prerelease: false
          
      - name: .Net Build
        uses: EasyDesk/action-dotnet-build@v1.0.0
