name: Build Universal

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Build Contracts
        run: |
          cd "KitX Contracts"

          cd "KitX.Contract.CSharp"
          dotnet build -c Release
          cd ".."

          cd ".."

      - name: Build Dashboard
        run: |
          cd "KitX Dashboard"
          dotnet build -c Release
          cd ".."

      - name: Build Rules
        run: |
          cd "KitX Rules"

          cd "KitX.Web.Rules"
          dotnet build -c Release
          cd ".."

          cd ".."

      - name: Build File Format Helper
        run: |
          cd "KitX File Format Helper"

          cd "KitX.KXP.Helper"
          dotnet build -c Release
          cd ".."

          cd ".."

  build-on-ubuntu:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Add to GitHub Repo
        run: |
          nuget sources add -name github -Source https://nuget.pkg.github.com/Crequency/index.json -Username Crequency -Password ${{ secrets.GitHubToken }}

      - name: Install NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: '6.x'

      - name: Build Contracts
        run: |
          cd "KitX Contracts"

          cd "KitX.Contract.CSharp"
          dotnet build -c Release
          cd ".."

          cd ".."

      - name: Build Dashboard
        run: |
          cd "KitX Dashboard"
          dotnet build -c Release
          cd ".."

      - name: Build Rules
        run: |
          cd "KitX Rules"

          cd "KitX.Web.Rules"
          dotnet build -c Release
          cd ".."

          cd ".."

      - name: Build File Format Helper
        run: |
          cd "KitX File Format Helper"

          cd "KitX.KXP.Helper"
          dotnet build -c Release
          cd ".."

          cd ".."

      - name: Publish Package to GitHub and NuGet
        run: |
          cd "KitX Build"

          nuget push ./Contracts/CSharp/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
          nuget push ./Contracts/CSharp/Release/*.nupkg -Source github -SkipDuplicate

          nuget push ./Rules/Web.Rules/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
          nuget push ./Rules/Web.Rules/Release/*.nupkg -Source github -SkipDuplicate

          nuget push "./File Format Helper/KXP/Release/*.nupkg" -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
          nuget push "./File Format Helper/KXP/Release/*.nupkg" -Source github -SkipDuplicate

          cd ".."

  build-on-macos:
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Build Contracts
        run: |
          cd "KitX Contracts"

          cd "KitX.Contract.CSharp"
          dotnet build -c Release
          cd ".."

          cd ".."

      - name: Build Dashboard
        run: |
          cd "KitX Dashboard"
          dotnet build -c Release
          cd ".."

      - name: Build Rules
        run: |
          cd "KitX Rules"

          cd "KitX.Web.Rules"
          dotnet build -c Release
          cd ".."

          cd ".."

      - name: Build File Format Helper
        run: |
          cd "KitX File Format Helper"

          cd "KitX.KXP.Helper"
          dotnet build -c Release
          cd ".."

          cd ".."


