name: Build Universal

on:
    push:
        branches:
            - main
        paths-ignore:
            - ".*/**"
            - "**/*.md"
    pull_request:
        branches:
            - main
        paths-ignore:
            - ".*/**"
            - "**/*.md"

    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: "true"

            - name: Setup .NET
              uses: actions/setup-dotnet@v2
              with:
                  dotnet-version: "6.0.x"
                  include-prerelease: false

            - name: Build Contracts
              working-directory: "KitX Standard/KitX Contracts"
              run: |
                  cd "KitX.Contract.CSharp"
                  dotnet build -c Release
                  cd ".."

            - name: Build Rules
              working-directory: "KitX Standard/KitX Rules"
              run: |
                  cd "KitX.Web.Rules"
                  dotnet build -c Release
                  cd ".."

            - name: Build File Format Helper
              working-directory: "KitX Standard/KitX File Formats"
              run: |
                  cd "KitX.File.Format.KXP"
                  dotnet build -c Release
                  cd ".."

            - name: Build Dashboard
              working-directory: "KitX Clients/KitX Dashboard/KitX Dashboard"
              run: |
                  dotnet build -c Release
