name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:
  build-on-windows:
    runs-on: windows-latest

    steps:
      # - uses: actions/checkout@v3

      # - name: Start
      #   run: echo Starting CI

      # - name: Descr
      #   run: |
      #     echo Building on Windows Latest
      #     echo --------------------------
          
      # - name: Setup .NET Core SDK
      #   uses: actions/setup-dotnet@v2.1.0
      #   with:
      #     dotnet-version: 6.0.x
      #     include-prerelease: false
          
      # - name: .Net Build
      #   uses: EasyDesk/action-dotnet-build@v1.0.0

      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
          include-prerelease: false

      - name: Build
        run: dotnet build -c Release

      # - name: Test
      #   run: dotnet test -c Release
