name: Build Universal

on:
    push:
        branches:
            - main
        paths-ignore:
            - ".*/**"
            - "**/*.md"
    pull_request:
        branches:
            - main
        paths-ignore:
            - ".*/**"
            - "**/*.md"

    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: dev=main
                  submodules: "true"

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: |
                      8.0.x

            - uses: actions/checkout@v4
            - run: |
                  cd "KitX Standard"
                  git submodule update --init --recursive

            - name: Build Contracts
              working-directory: "KitX Standard/KitX Contracts"
              run: |
                  cd "KitX.Contract.CSharp"
                  dotnet build -c Release

            - name: Build Shared
              working-directory: "KitX Standard/KitX.Shared"
              run: |
                  dotnet build -c Release

            - name: Build File Formats
              working-directory: "KitX Standard/KitX.FileFormats"
              run: |
                  dotnet build -c Release

            - name: Build Dashboard
              working-directory: "KitX Clients/KitX Dashboard/KitX Dashboard"
              run: |
                  dotnet build -c Release
