name: Build Plugins

on:
    push:
        branches:
            - main
        paths-ignore:
            - ".*/**"
            - "**/*.md"
    pull_request:
        branches:
            - main
        paths-ignore:
            - ".*/**"
            - "**/*.md"

    workflow_dispatch:

jobs:
    build-plugins-on-windows:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: dev=main
                  submodules: "true"

            - name: Checkout KitX Standard
              uses: actions/checkout@v4
              with:
                  repository: "Crequency/KitX-Standard"
                  ref: "dev=main"
                  path: "KitX Standard"
                  submodules: "true"

            - name: Checkout KitX SDK
              uses: actions/checkout@v4
              with:
                  repository: "Crequency/KitX-SDK"
                  ref: "dev=main"
                  path: "KitX SDK"
                  submodules: "true"

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: |
                      8.0.x

            - name: Build Plugins
              working-directory: "KitX SDK/KitX Plugins"
              run: |
                  cd "TestPlugin.CSharp"
                  dotnet build -c Release
                  cd ..

                  cd "TestPlugin.Winform.Core"
                  dotnet build -c Release
                  cd ..

                  cd "TestPlugin.WPF.Core"
                  dotnet build -c Release
                  cd ..
