name: Publish Packages

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

    workflow_dispatch:

jobs:
    build-on-ubuntu:
        runs-on: ubuntu-latest
        environment: Publish Packages
        if: contains(github.event.head_commit.message, '[Publish Packages]')

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: dev=main
                  submodules: "true"

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: |
                      8.0.x

            - uses: actions/checkout@v4
            - run: |
                  cd "KitX Standard"
                  git submodule update --init --recursive

            - uses: actions/checkout@v4
            - run: |
                  cd "KitX SDK"
                  git submodule update --init --recursive

            - name: Add to GitHub Repo
              run: |
                  nuget sources add -name github -Source https://nuget.pkg.github.com/Crequency/index.json -Username Crequency -Password ${{ secrets.GitHubToken }}

            - name: Install NuGet
              uses: nuget/setup-nuget@v1
              with:
                  nuget-version: "6.x"

            - name: Build and Publish `Cheese`
              working-directory: "KitX SDK/Cheese"
              if: contains(github.event.head_commit.message, '[Cheese]') || contains(github.event.head_commit.message, '[All]')
              run: |
                  dotnet build -c Release

                  nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
                  nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate

            - name: Build and Publish `KitX.Contract.CSharp`
              working-directory: "KitX Standard/KitX Contracts/KitX.Contract.CSharp"
              if: contains(github.event.head_commit.message, '[KitX.Contract.CSharp]') || contains(github.event.head_commit.message, '[All]')
              run: |
                  dotnet build -c Release

                  nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
                  nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate

            - name: Build and Publish `KitX.Shared`
              working-directory: "KitX Standard/KitX.Shared"
              if: contains(github.event.head_commit.message, '[KitX.Shared]') || contains(github.event.head_commit.message, '[All]')
              run: |
                  dotnet build -c Release

                  nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
                  nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate

            - name: Build and Publish `KitX.FileFormats`
              working-directory: "KitX Standard/KitX.FileFormats"
              if: contains(github.event.head_commit.message, '[KitX.FileFormats]') || contains(github.event.head_commit.message, '[All]')
              run: |
                  dotnet build -c Release

                  nuget push ./bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
                  nuget push ./bin/Release/*.nupkg -Source github -SkipDuplicate
